version: '3'
services:
  auditlimit:
    image: xyhelper/auditlimit
    restart: always
    ports:
      - "127.0.0.1:9611:8080"
    volumes:
      - ./data:/app/data
    environment:
      PORT: 9611
      OAIKEY: "" # OpenAI API key 用于内容审核
      DEFAULT: "20/3h"
      AUTO: "200/3h"
      TEXT-DAVINCI-002-RENDER-SHA: "200/3h"
      GPT-4O-MINI: "200/3h"
      GPT-4O: "60/3h"
      GPT-4: "20/3h"
      GPT-4O-CANMORE: "30/3h"
      O1-PRO: "7/24h"
      O3-PRO: "7/24h"
      O3: "7/24h"
      O4-MINI: "50/24h"
      O4-MINI-HIGH: "50/24h"
      RESEARCH: "2/24h"
    